version: '3.8'

services:
  streamlit_app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: 11_alpine_nation_performance
    ports:
      - "8507:8501"  # change port
    restart: always
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501

    volumes:
      - /etc/letsencrypt/live/dev.streamlit.swiss-ski.ch/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/dev.streamlit.swiss-ski.ch/privkey.pem:/certs/privkey.pem:ro
      - /secrets/secrets.toml:/.streamlit/secrets.toml:ro

